#pragma once

#include <cstdint>
#include <limits>

namespace BspParser::Enums {
  enum class Lump : uint32_t {
    Entities = 0,
    Planes = 1,
    TextureData = 2,
    Vertices = 3,
    Visibility = 4,
    Nodes = 5,
    TextureInfo = 6,
    Faces = 7,
    Lighting = 8,
    Occlusion = 9,
    Leaves = 10,
    FaceIds = 11,
    Edges = 12,
    SurfaceEdges = 13,
    Models = 14,
    WorldLights = 15,
    LeafFaces = 16,
    LeafBrushes = 17,
    Brushes = 18,
    BrushSides = 19,
    Areas = 20,
    AreaPortals = 21,
    Portals = 22,
    Unused0 = 22,
    PropCollision = 22,
    Clusters = 23,
    Unused1 = 23,
    PropHulls = 23,
    PortalVertices = 24,
    Unused2 = 24,
    PropHullVertices = 24,
    ClusterPortals = 25,
    Unused3 = 25,
    PropTriangles = 25,
    DisplacementInfo = 26,
    OriginalFaces = 27,
    PhysDisplacements = 28,
    PhysCollide = 29,
    VertexNormals = 30,
    VertexNormalIndices = 31,
    DisplacementLightmapAlphas = 32,
    DisplacementVertices = 33,
    DisplacementLightmapSamplePositions = 34,
    GameLump = 35,
    LeafWaterData = 36,
    Primitives = 37,
    PrimitiveVertices = 38,
    PrimitiveIndices = 39,
    PakFile = 40,
    ClipPortalVertices = 41,
    Cubemaps = 42,
    TextureDataStringData = 43,
    TextureDataStringTable = 44,
    Overlays = 45,
    LeafMinDistanceToWater = 46,
    FaceMacroTextureInfo = 47,
    DisplacementTriangles = 48,
    PhysCollideSurface = 49,
    PropBlob = 49,
    WaterOverlays = 50,
    LightmapPages = 51,
    LeafAmbientIndexHdr = 51,
    LightmapPageInfos = 52,
    LeafAmbientIndex = 52,
    LightingHdr = 53,
    WorldLightsHdr = 54,
    LeafAmbientLightingHdr = 55,
    LeafAmbientLighting = 56,
    XzipPakFile = 57,
    FacesHdr = 58,
    MapFlags = 59,
    OverlayFades = 60,
    OverlaySystemLevels = 61,
    PhysLevel = 62,
    DisplacementMultiblend = 63,
    None = std::numeric_limits<uint32_t>::max(),
  };

#define GAMELUMP_MAKE_CODE(a, b, c, d) ((a) << 24 | (b) << 16 | (c) << 8 | (d) << 0)
  enum class GameLumpID : int32_t {
    DetailProps = GAMELUMP_MAKE_CODE('d', 'p', 'r', 'p'),
    DetailPropLighting = GAMELUMP_MAKE_CODE('d', 'p', 'l', 't'),
    StaticProps = GAMELUMP_MAKE_CODE('s', 'p', 'r', 'p'),
    DetailPropLightingHdr = GAMELUMP_MAKE_CODE('d', 'p', 'l', 'h')
  };
#undef GAMELUMP_MAKE_CODE
}
