#pragma once

#include <cstdint>

namespace BSPEnums {
	enum class LUMP : uint32_t
	{
		ENTITIES,
		PLANES,
		TEXDATA,
		VERTICES,
		VISIBILITY,
		NODES,
		TEXINFO,
		FACES,
		LIGHTING,
		OCCLUSION,
		LEAFS,
		FACEIDS,
		EDGES,
		SURFEDGES,
		MODELS,
		WORLDLIGHTS,
		LEAFFACES,
		LEAFBRUSHES,
		BRUSHES,
		BRUSHSIDES,
		AREAS,
		AREAPORTALS,
		PORTALS,
		UNUSED0 = 22U,
		PROPCOLLISION = 22U,
		CLUSTERS,
		UNUSED1 = 23U,
		PROPHULLS = 23U,
		PORTALVERTS,
		UNUSED2 = 24U,
		PROPHULLVERTS = 24U,
		CLUSTERPORTALS,
		UNUSED3 = 25U,
		PROPTRIS = 25U,
		DISPINFO,
		ORIGINALFACES,
		PHYSDISP,
		PHYSCOLLIDE,
		VERTNORMALS,
		VERTNORMALINDICES,
		DISP_LIGHTMAP_ALPHAS,
		DISP_VERTS,
		DISP_LIGHTMAP_SAMPLE_POSITIONS,
		GAME_LUMP,
		LEAFWATERDATA,
		PRIMITIVES,
		PRIMVERTS,
		PRIMINDICES,
		PAKFILE,
		CLIPPORTALVERTS,
		CUBEMAPS,
		TEXDATA_STRING_DATA,
		TEXDATA_STRING_TABLE,
		OVERLAYS,
		LEAFMINDISTTOWATER,
		FACE_MACRO_TEXTURE_INFO,
		DISP_TRIS,
		PHYSCOLLIDESURFACE,
		PROP_BLOB = 49U,
		WATEROVERLAYS,
		LIGHTMAPPAGES,
		LEAF_AMBIENT_INDEX_HDR = 51U,
		LIGHTMAPPAGEINFOS,
		LEAF_AMBIENT_INDEX = 52U,
		LIGHTING_HDR,
		WORLDLIGHTS_HDR,
		LEAF_AMBIENT_LIGHTING_HDR,
		LEAF_AMBIENT_LIGHTING,
		XZIPPAKFILE,
		FACES_HDR,
		MAP_FLAGS,
		OVERLAY_FADES,
		OVERLAY_SYSTEM_LEVELS,
		PHYSLEVEL,
		DISP_MULTIBLEND
	};

	enum class SURF : int32_t
	{
		LIGHT = 0x1,
		SKY2D = 0x2,
		SKY = 0x4,
		WARP = 0x8,
		TRANS = 0x10,
		NOPORTAL = 0x20,
		TRIGGER = 0x40,
		NODRAW = 0x80,
		HINT = 0x100,
		SKIP = 0x200,
		NOLIGHT = 0x400,
		BUMPLIGHT = 0x800,
		NOSHADOWS = 0x1000,
		NODECALS = 0x2000,
		NOCHOP = 0x4000,
		HITBOX = 0x8000
	};

	inline SURF operator |(SURF lhs, SURF rhs)
	{
		return static_cast<SURF>(static_cast<int32_t>(lhs) | static_cast<int32_t>(rhs));
	}

	inline SURF& operator |=(SURF& lhs, SURF rhs)
	{
		lhs = lhs | rhs;
		return lhs;
	}
}
